version: '3'

services:
  mysql_docker:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
      - MYSQL_ROOT_HOST=%
    volumes:
      - /data/mysql
    ports:
      - 3306:3306
    #restart: 
    #   -always
  web:
    image: raenjamio/test-drive:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql_docker
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    restart: "always"
